#!/bin/bash

plancoincli config chain-id plancoin_final
plancoincli config node tcp://localhost:26657
plancoincli config trust-node true
plancoincli config output json
plancoincli config indent true

